### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by LyfeOnEdge** [AkdM/ssncpy#2]
Could you create an official release at [https://github.com/AkdM/ssncpy/releases](url)?
This would allow users to access it via the github api. You don't need to include a zip with the release, just marking a version as a release will allow the source to be accessed as it was at that point in time. I'd like to add your software as an optional download as well as use it to provide a graphical frontend with my app: https://github.com/LyfeOnEdge/HBUpdater
Thanks!

**Comment by AkdM** [comment]
Here you go! I just added v1.0.0 😃 
Let me know if that's enough for your needs.

**Comment by LyfeOnEdge** [comment]
That's perfect thanks
