### ISSUE TITLE
False status for Mariko units

### ISSUE THREAD

**Issue by el-emmo** [AkdM/ssncpy#4]
Checker gives a "warning" about Mariko switches (XKW, XKJ, etc.) which is not correct as those are clearly patched.

**Comment by AkdM** [comment]
Thanks for the feedback, that was indeed one of the required modifications I had to make.

`XKW1`, `XKJ1`, `XJW1`, `XWW1` are now marked as patched.

I have updated the DB (https://damota.me/ssnc/serials.json) as the default [config.ini](https://github.com/AkdM/ssncpy/blob/802515b00c2c26bddfab20efbd8c8468a8af6bd0/config.ini) file uses this. That also updates the used DB on the website version of the checker.
